-- ============================================================
-- UPGRADED SEED PROMPTS — Each prompt is highly specific
-- with unique use case, detailed variables, industry context,
-- step-by-step instructions, and no generic filler.
-- ============================================================
-- This migration REPLACES all existing prompts with better ones.
-- Run AFTER the original seed if you want fresh data.

DELETE FROM public.prompts;

INSERT INTO public.prompts (title, description, prompt_text, category, ai_tool, difficulty, premium, tags, upvotes, copies, views, created_at) VALUES

-- ──────────────────────────────────────────────────────
-- 1. LINKEDIN — B2B SaaS Thought Leadership
-- ──────────────────────────────────────────────────────
(
  'B2B SaaS Thought Leadership Post for LinkedIn',
  'Generate a data-driven LinkedIn thought leadership post specifically for B2B SaaS founders sharing counterintuitive industry insights. Includes hook formula, metric callouts, and engagement CTA.',
  E'You are a LinkedIn ghostwriter who has generated 50M+ impressions for B2B SaaS CEOs. Write a thought leadership post using this framework:\n\n**HOOK (Line 1):** Start with a counterintuitive stat or bold contrarian take about {industry_trend}. Pattern: "Everyone says X. The data says Y."\n\n**BODY:**\n1. Share a specific metric from your experience: "{metric_with_number}"\n2. Explain WHY this happens (root cause analysis in 2-3 sentences)\n3. Give 3 tactical takeaways, each starting with an action verb\n4. Include one real example (anonymised): "One of our clients, a {company_type} with {company_size} employees..."\n\n**CTA:** End with a polarising question that forces people to comment.\n\n**CONSTRAINTS:**\n- Exactly 150-200 words (LinkedIn algorithm sweet spot)\n- No hashtags in the post body (put 3-5 in first comment)\n- Use \\n\\n between every 1-2 sentences for mobile readability\n- Tone: Confident but not arrogant. Data-driven, not anecdotal.\n\nTopic: {topic}\nYour role/title: {your_title}\nTarget reader: {target_reader_role}\nKey metric to highlight: {metric_with_number}',
  'Social Media', 'ChatGPT', 'intermediate', false,
  ARRAY['linkedin', 'b2b', 'saas', 'thought-leadership', 'ghostwriting'],
  287, 1823, 6400, NOW()
),

-- ──────────────────────────────────────────────────────
-- 2. MIDJOURNEY — Cinematic Product Photography
-- ──────────────────────────────────────────────────────
(
  'Cinematic Product Photography for E-Commerce (Midjourney v6)',
  'Generate photorealistic product shots optimised for Midjourney v6 with specific camera settings, lighting rigs, and post-processing parameters. Perfect for DTC brands needing hero images.',
  E'Create a cinematic product photograph of {product_name} for a {brand_aesthetic} brand.\n\n**CAMERA SETUP:**\n- Camera: Phase One IQ4 150MP equivalent\n- Lens: {focal_length}mm prime, f/{aperture}\n- ISO: 50, Shutter: 1/125s\n- Aspect ratio: {aspect_ratio}\n\n**LIGHTING RIG:**\n- Key light: {key_light_type} at 45° camera-left, {key_light_modifier}\n- Fill: Negative fill (black V-flat) camera-right for dramatic shadow\n- Rim/hair light: Strip softbox 3/4 behind subject\n- Background: {background_description}\n\n**PRODUCT STYLING:**\n- Surface: {surface_material} with {surface_detail}\n- Props: {props_list}\n- Product angle: {camera_angle}\n- Hero detail to emphasise: {hero_detail}\n\n**POST-PROCESSING:**\n- Color grading: {color_grade_style}\n- Contrast: Medium-high\n- Skin/surface detail: Ultra-sharp with micro-contrast\n\n**NEGATIVE PROMPT:** No text, no watermarks, no blurry edges, no plastic look, no oversaturation\n\n--v 6.1 --ar {aspect_ratio} --style raw --s 250 --q 2',
  'Design', 'Midjourney', 'advanced', true,
  ARRAY['product-photography', 'ecommerce', 'midjourney-v6', 'dtc', 'hero-image'],
  198, 987, 4200, NOW()
),

-- ──────────────────────────────────────────────────────
-- 3. CLAUDE — Security-Focused Code Review for Node.js APIs
-- ──────────────────────────────────────────────────────
(
  'OWASP-Focused API Security Audit for Node.js/Express',
  'Get a comprehensive security review of your Express.js API code targeting OWASP Top 10 2025, with severity ratings, exploit scenarios, and exact fix code. Designed for senior backend engineers.',
  E'You are a principal application security engineer with 15 years experience in Node.js/Express security auditing and OWASP Top 10 expertise.\n\nAudit the following Express.js API code with this exact methodology:\n\n**STEP 1 — THREAT MODEL:**\nIdentify the API''s attack surface. List all entry points (routes, params, headers, body) and data flows.\n\n**STEP 2 — OWASP TOP 10 (2025) SCAN:**\nFor each applicable category, check:\n- A01: Broken Access Control — missing auth middleware, IDOR, privilege escalation\n- A02: Cryptographic Failures — hardcoded secrets, weak hashing, missing TLS\n- A03: Injection — SQL/NoSQL injection, command injection, XSS in API responses\n- A04: Insecure Design — missing rate limiting, no input validation schema\n- A05: Security Misconfiguration — CORS *, verbose errors in production, missing headers\n- A07: Authentication Failures — JWT without expiry, no refresh token rotation\n- A08: Data Integrity — no integrity checks on deserialized data\n- A09: Logging Failures — PII in logs, no audit trail\n- A10: SSRF — unvalidated URLs in fetch/axios calls\n\n**STEP 3 — OUTPUT FORMAT (for each finding):**\n```\n[SEVERITY: CRITICAL/HIGH/MEDIUM/LOW]\nVulnerability: {name}\nOWASP Category: {id}\nLocation: {file}:{line_range}\nExploit Scenario: {2-sentence attack description}\nCurrent Code: {vulnerable snippet}\nFixed Code: {corrected snippet with explanation}\nReferences: {CVE or CWE number}\n```\n\n**STEP 4 — SUMMARY TABLE:**\n| # | Severity | Finding | OWASP | Fix Effort |\n\n**CODE TO AUDIT:**\n```{language}\n{code}\n```\n\nFramework: Express.js {version}\nDatabase: {database}\nAuth method: {auth_method}\nDeployment: {deployment_target}',
  'Coding', 'Claude', 'advanced', true,
  ARRAY['security', 'owasp', 'nodejs', 'express', 'api-audit', 'code-review'],
  176, 654, 3100, NOW()
),

-- ──────────────────────────────────────────────────────
-- 4. CHATGPT — Instagram Carousel for Course Creators
-- ──────────────────────────────────────────────────────
(
  'High-Converting Instagram Carousel for Online Course Launches',
  'Create a 10-slide Instagram carousel script specifically designed for course creators launching digital products. Includes hook formulas, slide-by-slide copy with character counts, and design direction notes.',
  E'You are a top-tier Instagram content strategist who has created carousels with 1M+ reach for course creators and coaches.\n\nCreate a 10-slide Instagram carousel for launching "{course_name}" — a {course_format} course about {course_topic}.\n\n**TARGET AUDIENCE:** {audience_description}\n**PRICE POINT:** {price}\n**LAUNCH DATE:** {launch_date}\n\n**SLIDE-BY-SLIDE REQUIREMENTS:**\n\nSlide 1 (HOOK — most important):\n- Use pattern: "Stop {common_mistake}. Start {better_approach}."\n- Max 8 words on design\n- Design note: Bold text on gradient background, no image\n\nSlide 2-3 (PROBLEM):\n- Identify 2 specific pain points your audience has TODAY\n- Use "You" language, not "I"\n- Include a relatable micro-story (3 sentences max)\n\nSlide 4-6 (SOLUTION):\n- What they''ll learn (3 specific outcomes with metrics)\n- Format: "Module X: {title} → You''ll be able to {specific_result}"\n- Design note: Icon + short text per module\n\nSlide 7-8 (SOCIAL PROOF):\n- Testimonial from {testimonial_name}: "{testimonial_quote}"\n- Before/after transformation with numbers\n\nSlide 9 (OFFER):\n- Price, bonuses, guarantee\n- Urgency element: "{urgency_detail}"\n\nSlide 10 (CTA):\n- "Comment ''[KEYWORD]'' and I''ll send you the link"\n- Why comment > link in bio (algorithm boost)\n\n**CONSTRAINTS:**\n- Each slide: max 50 words\n- Emoji usage: 1-2 per slide, strategic not decorative\n- No jargon — write at 8th grade reading level\n- Include design direction notes in [brackets] for each slide',
  'Social Media', 'ChatGPT', 'beginner', false,
  ARRAY['instagram', 'carousel', 'course-launch', 'creator-economy', 'social-selling'],
  412, 2841, 8500, NOW()
),

-- ──────────────────────────────────────────────────────
-- 5. CHATGPT — SaaS Cold Email Drip (5-Touch)
-- ──────────────────────────────────────────────────────
(
  '5-Touch SaaS Cold Email Sequence with Personalisation Tokens',
  'Design a 5-email cold outreach drip campaign for B2B SaaS companies targeting specific ICP roles. Each email uses a different psychological framework (PAS, AIDA, BAB, etc.) with exact subject lines, preview text, and merge tokens.',
  E'You are a B2B cold email specialist who has achieved 45%+ open rates and 12%+ reply rates for SaaS companies.\n\nDesign a 5-email cold outreach sequence for {product_name}, a {product_type} SaaS that helps {value_proposition}.\n\n**ICP PROFILE:**\n- Title: {target_title} (e.g., VP of Engineering)\n- Company size: {company_size} employees\n- Industry: {industry}\n- Pain point: {primary_pain_point}\n- Current solution: {current_solution_they_use}\n\n**SEQUENCE STRUCTURE:**\n\n**Email 1 — Day 0 (Framework: Problem-Agitate-Solve)**\n- Subject: Max 5 words, lowercase, curiosity-driven\n- Preview text: 40 chars, complements subject\n- Body: 4 sentences max. Open with {{prospect_company}} specific observation.\n- CTA: Soft — "Worth a quick look?"\n\n**Email 2 — Day 3 (Framework: Before-After-Bridge)**\n- Subject: Reply to thread OR new angle\n- Body: Share a specific case study: "{{similar_company}} was {before_state}. After switching, {after_state} in {timeframe}."\n- CTA: "Can I share how?"\n\n**Email 3 — Day 7 (Framework: Social Proof)**\n- Subject: Use a number/metric\n- Body: Lead with ROI stat. Name-drop 2-3 recognisable customers.\n- Include: "{metric_proof}" (e.g., "reduced churn by 34%")\n- CTA: Calendar link — "15 min this week?"\n\n**Email 4 — Day 12 (Framework: Value-Add Breakup)**\n- Subject: "resource for {{prospect_first_name}}"\n- Body: Share a genuinely useful resource (blog, framework, calculator)\n- Subtle mention of product. No hard sell.\n- CTA: "Found this useful for teams like yours"\n\n**Email 5 — Day 18 (Framework: Permission-Based Close)**\n- Subject: "closing the loop"\n- Body: 2 sentences. "Should I close your file or is this still relevant?"\n- CTA: Binary choice — "Reply 1 for yes, 2 for not now"\n\n**RULES:**\n- No "I hope this email finds you well"\n- No "I/We" in first sentence of any email\n- Every email under 80 words\n- Merge tags: {{prospect_first_name}}, {{prospect_company}}, {{prospect_title}}\n- Test deliverability: no spam trigger words',
  'Marketing', 'ChatGPT', 'intermediate', false,
  ARRAY['cold-email', 'saas', 'b2b', 'outreach', 'drip-campaign', 'sales'],
  245, 1576, 5900, NOW()
),

-- ──────────────────────────────────────────────────────
-- 6. STABLE DIFFUSION — Fantasy Battle Scene
-- ──────────────────────────────────────────────────────
(
  'Epic Fantasy Battle Scene with Volumetric Lighting (SDXL)',
  'Generate a hyper-detailed fantasy battle illustration optimised for SDXL with specific LoRA suggestions, controlnet poses, and negative prompts. For game concept artists and fantasy illustrators.',
  E'Generate an epic fantasy battle scene with cinematic composition:\n\n**SCENE COMPOSITION:**\n- Foreground: {foreground_character} in dynamic {action_pose}, wearing {armor_description}\n- Midground: Clash between {faction_a} and {faction_b} armies\n- Background: {environment} with {atmospheric_effect}\n- Camera: Low-angle hero shot, Dutch tilt 15°\n\n**CHARACTER DETAIL:**\n- Race/species: {character_race}\n- Weapon: {weapon_type} with {magical_effect} enchantment\n- Expression: {emotion} — showing determination and battle fury\n- Armor material: {material} with battle damage and scratches\n\n**LIGHTING:**\n- Primary: Volumetric god rays from {light_source_position}\n- Secondary: {magical_color} magical glow emanating from weapon\n- Ambient: Warm firelight from burning structures\n- Atmosphere: Dust particles, ember sparks, smoke wisps\n\n**COLOR PALETTE:**\n- Dominant: {dominant_color}\n- Accent: {accent_color} (magical elements)\n- Shadows: Deep {shadow_tone}\n\n**TECHNICAL PARAMETERS:**\n- Style: {art_style} (e.g., Greg Rutkowski, Craig Mullins, Feng Zhu)\n- Quality tags: masterpiece, best quality, ultra detailed, 8k, sharp focus\n- Sampler: DPM++ 2M Karras\n- CFG Scale: 7-9\n- Steps: 30-50\n\n**NEGATIVE PROMPT:**\nlow quality, blurry, deformed hands, extra fingers, bad anatomy, watermark, text, signature, cropped, worst quality, jpeg artifacts, duplicate, morbid, mutilated, poorly drawn face\n\n**SUGGESTED LoRAs:**\n- Detail enhancer LoRA (weight 0.6)\n- Fantasy armor LoRA (weight 0.5)\n- Epic lighting LoRA (weight 0.7)',
  'Design', 'Stable Diffusion', 'intermediate', false,
  ARRAY['fantasy', 'battle-scene', 'sdxl', 'concept-art', 'game-art', 'illustration'],
  267, 1234, 4100, NOW()
),

-- ──────────────────────────────────────────────────────
-- 7. CLAUDE — API Documentation Generator for REST APIs
-- ──────────────────────────────────────────────────────
(
  'OpenAPI-Compliant REST API Documentation Generator',
  'Generate comprehensive API docs from code that includes OpenAPI 3.1 schemas, authentication flows, rate limit tables, error code references, and SDK code examples in 4 languages. For developer experience teams.',
  E'You are a senior technical writer specialising in developer documentation for API-first companies.\n\nGenerate OpenAPI 3.1-compliant documentation for the {api_name} REST API.\n\n**API CONTEXT:**\n- Base URL: {base_url}\n- Auth: {auth_type} (e.g., Bearer token, API key in header, OAuth 2.0)\n- Rate limit: {rate_limit} requests per {rate_window}\n- Versioning: {versioning_strategy}\n\n**FOR EACH ENDPOINT, GENERATE:**\n\n```yaml\n# OpenAPI 3.1 format\npaths:\n  {path}:\n    {method}:\n      summary: {one_line_description}\n      description: {detailed_description_with_use_case}\n      operationId: {operation_id}\n      tags: [{tag}]\n      security: [{auth_requirement}]\n      parameters: {list_with_types_descriptions_required_flag}\n      requestBody:\n        content:\n          application/json:\n            schema: {json_schema_with_examples}\n      responses:\n        200: {success_response_with_example}\n        400: {validation_error_example}\n        401: {auth_error}\n        429: {rate_limit_error}\n        500: {server_error}\n```\n\n**CODE EXAMPLES (for each endpoint):**\n\n1. **cURL** — with all headers and body\n2. **Python (requests)** — with error handling\n3. **JavaScript (fetch)** — async/await with try/catch\n4. **Go (net/http)** — idiomatic Go with struct marshalling\n\n**ADDITIONAL SECTIONS:**\n- Authentication guide (step-by-step with screenshots description)\n- Error code reference table: | Code | Meaning | Resolution |\n- Rate limiting guide with retry-after header handling\n- Webhook events (if applicable)\n- Changelog format\n\n**ENDPOINTS TO DOCUMENT:**\n{endpoints_list}\n\n**TONE:** Developer-friendly, concise, example-heavy. Assume reader knows HTTP basics but not your API.',
  'Coding', 'Claude', 'intermediate', true,
  ARRAY['api-docs', 'openapi', 'technical-writing', 'developer-experience', 'rest-api'],
  189, 832, 3800, NOW()
),

-- ──────────────────────────────────────────────────────
-- 8. CHATGPT — YouTube Retention-Optimised Script
-- ──────────────────────────────────────────────────────
(
  'YouTube Script with Retention Hooks Every 60 Seconds',
  'Write a retention-optimised YouTube script with built-in pattern interrupts, B-roll callouts, timestamp markers, and audience retention graph predictions. For creators targeting 50%+ average view duration.',
  E'You are a YouTube scriptwriter who has written scripts for channels with 1M+ subscribers, achieving 55%+ average view duration.\n\nWrite a {video_length}-minute YouTube script about "{video_title}".\n\n**CHANNEL CONTEXT:**\n- Niche: {niche}\n- Audience: {audience_demographic}\n- Average current AVD: {current_avd}%\n- Competitor reference: {competitor_channel}\n\n**SCRIPT STRUCTURE:**\n\n**[0:00-0:03] COLD OPEN (No intro!):**\n- Start mid-sentence with the most shocking/valuable moment\n- Pattern: "What if I told you {shocking_claim}?"\n- [B-ROLL: {visual_suggestion}]\n\n**[0:03-0:30] HOOK + PROMISE:**\n- State the problem in ONE sentence\n- Promise what they''ll learn: "By the end of this video, you''ll know exactly how to {specific_outcome}"\n- Anti-click-away: "And at {timestamp}, I''ll show you {teaser}"\n\n**[0:30-1:00] CONTEXT:**\n- Why this matters NOW (timely relevance)\n- Quick credibility: "After {experience_proof}..."\n- [RETENTION HOOK: "But first, let me show you something most people miss"]\n\n**[1:00-{midpoint}] MAIN CONTENT:**\nBreak into {section_count} sections. For each:\n- Section title [ON SCREEN TEXT]\n- Key insight with example\n- [PATTERN INTERRUPT every 60 seconds]: Use one of:\n  - "Here''s where it gets interesting..."\n  - [B-ROLL SHIFT]\n  - Direct question to viewer\n  - Unexpected visual/graphic\n  - "Now pay attention to this part..."\n\n**[{midpoint}] MID-ROLL RETENTION SAVE:**\n- "We''re halfway through, and the best part is coming up at {timestamp}"\n\n**[Last 2 min] PAYOFF:**\n- Deliver the biggest promise\n- "Now here''s what nobody tells you..."\n\n**[Last 30 sec] CTA:**\n- One specific CTA only (subscribe OR video OR comment — not all three)\n- End screen: Recommend {related_video_topic}\n\n**FORMATTING RULES:**\n- [TIMESTAMPS] before each section\n- [B-ROLL: description] for editor\n- [ON SCREEN: text] for graphics\n- [SFX: sound] for audio cues\n- Write conversationally — read it aloud test\n- Flesch reading ease: 70+ (8th grade level)\n\nTopic: {topic}\nVideo goal: {goal}\nTone: {tone}',
  'Content Writing', 'ChatGPT', 'intermediate', false,
  ARRAY['youtube', 'script', 'retention', 'content-creation', 'video-production'],
  303, 2067, 7100, NOW()
),

-- ──────────────────────────────────────────────────────
-- 9. CHATGPT — Brand Strategy for Startup Seed Stage
-- ──────────────────────────────────────────────────────
(
  'Seed-Stage Startup Brand Identity & Positioning Framework',
  'Develop a complete brand identity system for seed-stage startups including positioning matrix, voice guidelines, naming conventions, and launch messaging. Built for founders who need investor-ready brand docs.',
  E'You are a brand strategist from a top agency (Pentagram/Wolff Olins level) working with a seed-stage startup.\n\nDevelop a complete brand identity framework for {company_name}.\n\n**COMPANY BRIEF:**\n- Product: {product_description}\n- Industry: {industry}\n- Stage: Seed / Pre-Series A\n- Funding: {funding_amount}\n- Founders: {founder_backgrounds}\n- Current customers: {customer_count}\n\n**DELIVERABLES:**\n\n**1. POSITIONING MATRIX:**\n| Dimension | Our Position | Competitor A | Competitor B |\n|-----------|-------------|-------------|-------------|\n| Price     |             |             |             |\n| Speed     |             |             |             |\n| Quality   |             |             |             |\n| Target    |             |             |             |\n\n**2. BRAND POSITIONING STATEMENT (Madison & Vine format):**\n"For [target audience] who [need/pain point], {company_name} is the [category] that [key benefit] because [reason to believe]."\n\n**3. MISSION / VISION / VALUES:**\n- Mission: [action-oriented, present tense, max 15 words]\n- Vision: [aspirational, future state, max 20 words]\n- Values: [5 values with 1-sentence explanation each]\n\n**4. BRAND PERSONALITY (Aaker model):**\nRate 1-5 on: Sincerity, Excitement, Competence, Sophistication, Ruggedness\nWith justification for each.\n\n**5. VOICE & TONE GUIDELINES:**\n| Context | Tone | Example Do | Example Don''t |\n|---------|------|-----------|---------------|\n| Website | | | |\n| Email | | | |\n| Social | | | |\n| Support | | | |\n| Investor pitch | | | |\n\n**6. MESSAGING HIERARCHY:**\n- Tagline (max 6 words)\n- Elevator pitch (30 seconds / 75 words)\n- Boilerplate (press release style, 100 words)\n- Investor one-liner\n\n**7. VISUAL DIRECTION:**\n- Primary color + meaning\n- Secondary palette (3 colors)\n- Typography direction (serif vs sans, modern vs classic)\n- Photography/illustration style\n- Logo direction (wordmark vs symbol vs combo)\n\n**8. NAMING CONVENTIONS:**\n- Product naming pattern\n- Feature naming pattern\n- Content naming pattern\n\nCompetitors to differentiate from: {competitors}',
  'Business', 'ChatGPT', 'advanced', true,
  ARRAY['brand-strategy', 'startup', 'positioning', 'seed-stage', 'identity-design'],
  156, 678, 2300, NOW()
),

-- ──────────────────────────────────────────────────────
-- 10. CHATGPT — Programmatic SEO Content Brief
-- ──────────────────────────────────────────────────────
(
  'Programmatic SEO Content Brief with NLP Entity Targeting',
  'Generate a data-driven content brief that targets specific NLP entities, includes TF-IDF keyword mapping, SERP intent analysis, and internal linking strategy. For SEO teams scaling content production.',
  E'You are a senior SEO strategist specialising in programmatic content at scale (1,000+ pages/month).\n\nCreate a comprehensive content brief for the target keyword: "{primary_keyword}"\n\n**KEYWORD RESEARCH:**\n- Primary keyword: {primary_keyword}\n- Estimated monthly search volume: {search_volume}\n- Keyword difficulty: {kd_score}/100\n- CPC: ${cpc}\n- Search intent: {intent_type} (informational/commercial/transactional/navigational)\n\n**SERP ANALYSIS:**\nAnalyse the current top 5 results and identify:\n1. Content format (listicle, guide, comparison, tool)\n2. Average word count of ranking pages\n3. Common H2/H3 headings across results\n4. Content gaps (topics top results miss)\n5. Featured snippet opportunity type\n\n**CONTENT BRIEF:**\n\n1. **Meta Title:** {50-60 chars, keyword-front-loaded}\n2. **Meta Description:** {150-160 chars, includes CTA}\n3. **URL Slug:** /{optimised_slug}\n4. **Target Word Count:** {word_count} words\n5. **Content Type:** {content_format}\n\n6. **OUTLINE (H2/H3 structure):**\n   - H1: {title}\n   - H2: {section_1} [target: {lsi_keyword_1}]\n     - H3: {subsection}\n   - H2: {section_2} [target: {lsi_keyword_2}]\n   - ... (minimum 6 H2 sections)\n\n7. **NLP ENTITIES TO INCLUDE:**\n   List 15-20 entities Google expects in content about this topic:\n   | Entity | Type | Prominence (1-3) |\n\n8. **TF-IDF KEYWORD MAP:**\n   | Keyword | Target Frequency | Current Top-Page Avg |\n   (Include 20+ LSI keywords)\n\n9. **INTERNAL LINKING:**\n   - Pages to link TO from this content: {internal_links}\n   - Pages that should link BACK to this content: {backlink_sources}\n\n10. **SCHEMA MARKUP:** Recommend appropriate schema (FAQ, HowTo, Article)\n\n11. **VISUAL ASSETS NEEDED:**\n    - Custom graphics: {list}\n    - Screenshots: {list}\n    - Data visualizations: {list}\n\n12. **COMPETITOR CONTENT TO BEAT:**\n    - URL: {competitor_url}\n    - Their word count: {word_count}\n    - What they do well:\n    - What they miss (our opportunity):\n\nNiche: {niche}\nWebsite domain: {domain}',
  'Content Writing', 'ChatGPT', 'advanced', false,
  ARRAY['seo', 'content-brief', 'programmatic-seo', 'nlp', 'keyword-research'],
  389, 2456, 8800, NOW()
),

-- ──────────────────────────────────────────────────────
-- 11. CHATGPT — Product Hunt Launch Day Playbook
-- ──────────────────────────────────────────────────────
(
  'Product Hunt Launch Day Playbook (Top 5 Strategy)',
  'Complete Product Hunt launch plan with hour-by-hour timeline, maker comment strategy, community activation templates, and social media amplification scripts. For indie makers targeting Top 5.',
  E'You are a Product Hunt launch strategist who has helped 15+ products reach #1 Product of the Day.\n\nCreate a complete launch playbook for {product_name}: {product_one_liner}.\n\n**PRE-LAUNCH (7 days before):**\n\n1. **Teaser Campaign:**\n   - Ship page copy (tagline + 3 key benefits)\n   - "Coming soon" social posts (Twitter, LinkedIn templates)\n   - DM template to send 50+ supporters:\n     "Hey {name}, I''m launching {product_name} on PH next {day}. It {value_prop}. Would love your support! I''ll send you the link at midnight PT. 🚀"\n\n2. **Asset Prep:**\n   - Thumbnail: {thumbnail_description} (240x240)\n   - Gallery: 5 images showing {key_features}\n   - Video: 1-min demo script outline\n   - First comment (maker comment): 150 words explaining WHY you built this\n\n**LAUNCH DAY (Hour by Hour, Pacific Time):**\n\n| Time (PT) | Action | Platform | Template |\n|-----------|--------|----------|----------|\n| 12:01 AM | Submit | PH | — |\n| 12:05 AM | Post maker comment | PH | {maker_comment_template} |\n| 6:00 AM | Twitter thread | Twitter | 7-tweet thread template |\n| 7:00 AM | LinkedIn post | LinkedIn | Storytelling post |\n| 8:00 AM | Activate DM list | All | "We''re live! {link}" |\n| 10:00 AM | Reply to every comment | PH | Personalised responses |\n| 12:00 PM | Midday push | Twitter | Progress update |\n| 3:00 PM | Community posts | Reddit/Discord/Slack | {community_templates} |\n| 6:00 PM | Thank you + momentum | Twitter | Milestone celebration |\n| 11:00 PM | Final push | All | "Last 1 hour!" |\n\n**MAKER COMMENT TEMPLATE:**\n"Hey PH! 👋\\n\\nI''m {your_name}, and I built {product_name} because {personal_story_2_sentences}.\\n\\nThe problem: {problem}\\n\\nWhat makes us different:\\n✅ {differentiator_1}\\n✅ {differentiator_2}\\n✅ {differentiator_3}\\n\\n🎁 Special for PH: {launch_offer}\\n\\nI''d love your feedback. AMA! 🙏"\n\n**POST-LAUNCH (48 hours after):**\n- Thank you email to supporters\n- Blog post: "How we launched on Product Hunt"\n- Social proof collection and testimonial requests\n\nProduct: {product_name}\nCategory: {product_category}\nTarget PH audience: {target_audience}\nLaunch offer: {launch_offer}',
  'Marketing', 'ChatGPT', 'intermediate', false,
  ARRAY['product-hunt', 'launch', 'indie-maker', 'saas-launch', 'go-to-market'],
  267, 1345, 4800, NOW()
),

-- ──────────────────────────────────────────────────────
-- 12. CHATGPT — Podcast Interview Prep & Script
-- ──────────────────────────────────────────────────────
(
  'Podcast Interview Prep Kit with Guest Research & Question Flow',
  'Generate a complete podcast interview preparation kit including guest research brief, warm-up questions, segmented question flow with follow-up branches, and post-interview action items. For podcast hosts doing 2+ interviews per week.',
  E'You are a podcast producer for a top-50 business podcast with 500K+ downloads per episode.\n\nCreate a complete interview prep kit for an episode with {guest_name}.\n\n**GUEST RESEARCH BRIEF:**\n- Guest: {guest_name}\n- Title: {guest_title} at {guest_company}\n- Known for: {guest_known_for}\n- Recent news/content: {recent_content}\n- Social media presence: {social_handles}\n- Previous podcast appearances: Research and list 3 recent ones\n- Topics they''re passionate about: {passion_topics}\n- Controversial takes they''ve shared: {hot_takes}\n\n**PRE-INTERVIEW (5 min before recording):**\nWarm-up questions (off-air):\n1. "What''s something you''ve been excited about this week?"\n2. "Is there anything you definitely want to mention today?"\n3. "Any topics that are off-limits?"\n\n**INTERVIEW FLOW ({episode_duration} minutes):**\n\n**Segment 1 — Origin Story (0:00-{seg1_end}):**\n- Q1: {opening_question} — [NOTE: Start with something unexpected, NOT "tell us about yourself"]\n- Q2: Follow-up branch A (if they mention {topic_a}): {follow_up_a}\n- Q2: Follow-up branch B (if they mention {topic_b}): {follow_up_b}\n\n**Segment 2 — Deep Dive: {core_topic} ({seg1_end}-{seg2_end}):**\n- Q3: {deep_question_1}\n- Q4: {deep_question_2}\n- Q5: Challenge question: "Some people would argue {counterpoint}. How do you respond?"\n- [TRANSITION: "That''s fascinating. Let me shift gears to..."]\n\n**Segment 3 — Tactical / Actionable ({seg2_end}-{seg3_end}):**\n- Q6: "If someone listening wanted to {specific_action}, what are the exact first 3 steps?"\n- Q7: "What''s a tool or resource you use every day that most people don''t know about?"\n- Q8: "What''s a mistake you see {audience_type} making repeatedly?"\n\n**Segment 4 — Rapid Fire ({seg3_end}-{seg4_end}):**\n- Best book this year?\n- One piece of advice for your 25-year-old self?\n- What''s overrated in {industry}?\n- What''s underrated?\n- Where can people find you?\n\n**POST-INTERVIEW CHECKLIST:**\n- [ ] Send thank-you DM within 1 hour\n- [ ] Share 3 quote graphics on social tagging guest\n- [ ] Create show notes with timestamps\n- [ ] Draft email to guest with episode link\n\nPodcast: {podcast_name}\nAudience: {listener_demographic}\nTone: {tone}',
  'Content Writing', 'ChatGPT', 'intermediate', false,
  ARRAY['podcast', 'interview', 'content-production', 'media', 'journalism'],
  134, 567, 2100, NOW()
),

-- ──────────────────────────────────────────────────────
-- 13. CHATGPT — Technical Interview Simulator (System Design)
-- ──────────────────────────────────────────────────────
(
  'System Design Interview Simulator for FAANG-Level Roles',
  'Interactive system design interview simulator that walks through a complete 45-minute system design round with trade-off analysis, capacity estimation, and architecture diagram descriptions. For engineers targeting L5+ roles.',
  E'You are a Staff Engineer at {target_company} conducting a 45-minute system design interview for an {level} position.\n\n**INTERVIEW SETUP:**\n- Problem: Design {system_name} (e.g., "Design Twitter''s real-time feed", "Design Uber''s ride matching")\n- Level: {level} (L5/L6/Staff/Principal)\n- Focus areas: {focus_areas}\n\n**CONDUCT THE INTERVIEW IN PHASES:**\n\n**Phase 1 — Requirements Clarification (5 min):**\nPresent the problem, then WAIT for my questions. After I ask, provide:\n- Functional requirements (5-7 specific features)\n- Non-functional requirements (latency, availability, consistency)\n- Scale constraints:\n  - DAU: {dau}\n  - Peak QPS: {peak_qps}\n  - Data volume: {data_volume}/day\n  - Read:Write ratio: {rw_ratio}\n\n**Phase 2 — Capacity Estimation (5 min):**\nGuide me through:\n- Storage calculation\n- Bandwidth estimation\n- Cache sizing\n- If I make errors, hint: "That seems off — double-check your {calculation}"\n\n**Phase 3 — High-Level Design (10 min):**\n- Describe the architecture verbally (I''ll draw)\n- Prompt me: "Walk me through the main components"\n- After my proposal, follow up with: "What happens when {failure_scenario}?"\n\n**Phase 4 — Deep Dive (15 min):**\nPick the most critical component and ask:\n- "How would you handle {specific_challenge}?"\n- "What database would you choose and why?"\n- "How do you handle {consistency_vs_availability}?"\n- Push back on my answers: "But what about {edge_case}?"\n\n**Phase 5 — Trade-offs & Wrap-up (10 min):**\n- "What are the bottlenecks in your design?"\n- "How would you scale this to 10x current load?"\n- "What would you monitor in production?"\n\n**EVALUATION RUBRIC (share at the end):**\n| Criteria | Score (1-5) | Notes |\n|----------|------------|-------|\n| Requirements gathering | | |\n| Capacity estimation accuracy | | |\n| Component design | | |\n| Data model design | | |\n| Trade-off analysis | | |\n| Communication clarity | | |\n| Handling follow-ups | | |\n\n**OVERALL VERDICT:** Hire / Lean Hire / Lean No Hire / No Hire\n\n**IMPORTANT:** Act as a REAL interviewer — don''t give answers. Ask follow-up questions. Push back. Let me struggle. Only hint if I''m completely stuck for 2+ minutes.',
  'Coding', 'ChatGPT', 'advanced', true,
  ARRAY['system-design', 'interview', 'faang', 'architecture', 'senior-engineer'],
  298, 1392, 5400, NOW()
),

-- ──────────────────────────────────────────────────────
-- 14. CHATGPT — Instagram Reels Hook + Caption
-- ──────────────────────────────────────────────────────
(
  'Instagram Reels Hook Script with Trending Audio Strategy',
  'Write a 15-60 second Instagram Reels script with a scroll-stopping hook, visual shot list, trending audio pairing suggestions, and caption with hashtag strategy. For creators and brands targeting Explore page.',
  E'You are an Instagram Reels strategist who has created Reels with 10M+ views for DTC brands and personal brands.\n\nCreate a complete Reels package for a {reel_duration}-second Reel about "{reel_topic}".\n\n**ACCOUNT CONTEXT:**\n- Niche: {niche}\n- Followers: {follower_count}\n- Content style: {content_style}\n- Target: Get on Explore page\n\n**REEL SCRIPT:**\n\n**[0:00-0:03] HOOK (Most critical 3 seconds):**\nChoose one hook type:\n- Text hook on screen: "{hook_text}" (max 8 words, high contrast)\n- Verbal hook: Start with "POV:", "Wait for it", or "Stop scrolling if {condition}"\n- Visual hook: {visual_hook_description}\n\n**[0:03-0:05] CONTEXT:**\n- Quick setup in 1 sentence\n- On-screen text: {context_text}\n\n**[0:05-{main_end}] MAIN CONTENT:**\n| Timestamp | Visual | Audio/Voiceover | On-Screen Text |\n|-----------|--------|-----------------|----------------|\n| 0:05 | {shot_1} | {audio_1} | {text_1} |\n| {ts_2} | {shot_2} | {audio_2} | {text_2} |\n| {ts_3} | {shot_3} | {audio_3} | {text_3} |\n(Continue for full duration)\n\n**[Last 3 sec] PAYOFF:**\n- Reveal / punchline / transformation\n- End frame: "Follow for more {niche} tips"\n\n**TRENDING AUDIO SUGGESTIONS (3 options):**\n1. {audio_suggestion_1} — why it works for this content\n2. {audio_suggestion_2} — trending this week\n3. Original audio option — voiceover style: {voiceover_style}\n\n**CAPTION:**\n- Line 1 (hook): {caption_hook}\n- Body: 2-3 sentences expanding on the value\n- CTA: {caption_cta}\n- Emojis: Strategic, max 3\n\n**HASHTAG STRATEGY (in first comment):**\n- 3 big hashtags (1M+ posts): {big_hashtags}\n- 3 medium (100K-1M): {medium_hashtags}\n- 4 niche (10K-100K): {niche_hashtags}\n\n**POSTING STRATEGY:**\n- Best time: {optimal_posting_time}\n- Reply to first 10 comments within 30 min\n- Share to Stories with poll sticker\n\nTone: {tone}\nBrand voice: {brand_voice}',
  'Social Media', 'ChatGPT', 'beginner', false,
  ARRAY['instagram-reels', 'short-form-video', 'trending', 'explore-page', 'social-media'],
  354, 2200, 7800, NOW()
),

-- ──────────────────────────────────────────────────────
-- 15. CLAUDE — Research Paper Analysis & Summary
-- ──────────────────────────────────────────────────────
(
  'Academic Research Paper Deep Analysis with Methodology Critique',
  'Break down a research paper with structured analysis of methodology, statistical validity, bias assessment, and practical implications. For PhD students, researchers, and science communicators.',
  E'You are a peer reviewer for Nature/Science-tier journals with expertise in {field_of_study}.\n\nAnalyse the following research paper with academic rigour:\n\n**PAPER DETAILS:**\n- Title: "{paper_title}"\n- Authors: {authors}\n- Journal/Source: {journal}\n- Year: {year}\n- DOI: {doi}\n\n**ANALYSIS FRAMEWORK:**\n\n**1. EXECUTIVE SUMMARY (1 paragraph, 100 words):**\nWhat did they study, how, and what did they find? Written for an educated non-specialist.\n\n**2. RESEARCH QUESTION & HYPOTHESIS:**\n- Primary research question\n- Hypothesis (explicit or implicit)\n- How this fills a gap in existing literature\n\n**3. METHODOLOGY CRITIQUE:**\n| Aspect | Assessment | Concern Level |\n|--------|-----------|---------------|\n| Sample size | {adequate/small/large} | {low/medium/high} |\n| Sampling method | {random/convenience/stratified} | |\n| Control group | {present/absent/inadequate} | |\n| Blinding | {single/double/none} | |\n| Duration | {sufficient/insufficient} | |\n| Reproducibility | {described/vague/missing} | |\n\n**4. STATISTICAL ANALYSIS:**\n- Methods used: {list_statistical_methods}\n- p-values: Are they meaningful or p-hacked?\n- Effect sizes: Reported? Practically significant?\n- Confidence intervals: Reported?\n- Multiple comparisons correction: Applied?\n\n**5. BIAS ASSESSMENT (Cochrane-style):**\n- Selection bias: {low/unclear/high}\n- Performance bias: {low/unclear/high}\n- Detection bias: {low/unclear/high}\n- Attrition bias: {low/unclear/high}\n- Reporting bias: {low/unclear/high}\n- Funding bias: Check funding sources\n\n**6. KEY FINDINGS (numbered, specific):**\n- Finding 1: {with exact numbers/stats}\n- Finding 2: ...\n- Surprising finding: ...\n\n**7. LIMITATIONS (author-stated + your additions):**\n- Authors acknowledge: {list}\n- Additional limitations I identify: {list}\n\n**8. PRACTICAL IMPLICATIONS:**\n- For practitioners in {field}: {implications}\n- For future research: {suggestions}\n- For public understanding: {key_takeaway}\n\n**9. RELATED WORK:**\n- 3 papers that support these findings\n- 2 papers that contradict these findings\n\n**10. OVERALL ASSESSMENT:**\n- Quality score: {1-10}/10\n- Novelty: {low/medium/high}\n- Impact: {low/medium/high}\n- Recommendation: {accept/minor revision/major revision/reject}\n\n{paper_content_or_abstract}',
  'Learning', 'Claude', 'advanced', false,
  ARRAY['research', 'academic', 'peer-review', 'methodology', 'science', 'phd'],
  223, 856, 3900, NOW()
),

-- ──────────────────────────────────────────────────────
-- 16. CHATGPT — Job Application Letter (Specific Industry)
-- ──────────────────────────────────────────────────────
(
  'Tailored Cover Letter for Tech Industry with ATS Optimisation',
  'Generate a cover letter that passes ATS screening, matches specific job description keywords, and tells a compelling career narrative. Includes keyword extraction and match percentage analysis.',
  E'You are a career coach and former tech recruiter who has reviewed 50,000+ applications at FAANG companies.\n\nWrite an ATS-optimised cover letter for this specific role:\n\n**JOB DETAILS:**\n- Position: {position_title}\n- Company: {company_name}\n- Department: {department}\n- Job description key requirements:\n{job_description_paste}\n\n**MY PROFILE:**\n- Current role: {current_role} at {current_company}\n- Years of experience: {years_experience}\n- Key skills: {skills_list}\n- Top 3 achievements:\n  1. {achievement_1_with_metrics}\n  2. {achievement_2_with_metrics}\n  3. {achievement_3_with_metrics}\n- Education: {education}\n- Why this company: {motivation}\n\n**COVER LETTER STRUCTURE:**\n\n**Paragraph 1 — Hook (3 sentences max):**\n- Do NOT start with "I am writing to apply"\n- Start with a company-specific insight or shared value\n- Name the exact role\n\n**Paragraph 2 — Relevance (4-5 sentences):**\n- Match 3 JD requirements to your experience\n- Use the STAR format (compressed): Situation → Action → Result\n- Include QUANTIFIED results\n\n**Paragraph 3 — Cultural Add (3 sentences):**\n- Reference company culture/values from their careers page\n- Explain how you ADD to the culture (not "fit")\n\n**Paragraph 4 — Close (2 sentences):**\n- Confident but not presumptuous\n- Specific next step: "I''d welcome 20 minutes to discuss how {specific_skill} can help {company} achieve {goal}"\n\n**ATS OPTIMISATION:**\nAfter the letter, provide:\n1. **Keyword Match Analysis:**\n   | JD Keyword | Used in Letter? | Frequency |\n   Extract top 15 keywords from JD and check coverage\n\n2. **Match Score:** {percentage}% keyword match\n3. **Missing Keywords:** List any critical ones to add\n4. **Formatting:** No headers, no tables, no special characters — plain text ATS-safe\n\n**CONSTRAINTS:**\n- 250-350 words (recruiter attention span)\n- No clichés: "passionate", "team player", "go-getter"\n- Active voice only\n- Company name mentioned 2-3 times',
  'Career', 'ChatGPT', 'beginner', false,
  ARRAY['cover-letter', 'job-application', 'ats', 'tech-career', 'resume'],
  289, 1723, 5500, NOW()
),

-- ──────────────────────────────────────────────────────
-- 17. CHATGPT — SaaS Product Comparison Matrix
-- ──────────────────────────────────────────────────────
(
  'SaaS Tool Comparison Matrix with TCO Analysis & Migration Risk',
  'Create a comprehensive SaaS comparison including TCO calculations, migration risk scores, feature-by-feature matrix, and a weighted decision framework. For CTOs and procurement teams evaluating vendors.',
  E'You are a SaaS procurement consultant who has evaluated 200+ enterprise software purchases.\n\nCreate a comprehensive comparison of {tool_a} vs {tool_b} (optionally vs {tool_c}) for {use_case}.\n\n**EVALUATION CONTEXT:**\n- Team size: {team_size}\n- Budget: {annual_budget}/year\n- Current tool: {current_tool}\n- Must-have features: {must_haves}\n- Nice-to-have features: {nice_to_haves}\n- Integration requirements: {integrations}\n- Compliance needs: {compliance}\n\n**COMPARISON MATRIX:**\n\n| Feature | {tool_a} | {tool_b} | Weight (1-5) |\n|---------|----------|----------|-------------|\n| {feature_1} | ✅/⚠️/❌ + detail | | |\n| {feature_2} | | | |\n| ... (minimum 15 features) | | | |\n\n**TOTAL COST OF OWNERSHIP (3-Year):**\n\n| Cost Component | {tool_a} | {tool_b} |\n|---------------|----------|----------|\n| License (per user/month) | | |\n| Implementation/setup | | |\n| Training (hours × rate) | | |\n| Migration (data + workflow) | | |\n| Integration development | | |\n| Ongoing maintenance | | |\n| Hidden costs (overages, add-ons) | | |\n| **3-Year Total** | | |\n\n**MIGRATION RISK ASSESSMENT:**\n| Risk Factor | {tool_a} | {tool_b} |\n|-------------|----------|----------|\n| Data export capability | {easy/moderate/difficult} | |\n| API completeness | | |\n| Vendor lock-in risk | {low/medium/high} | |\n| Learning curve | | |\n| Downtime during migration | | |\n| **Overall Risk Score** | /10 | /10 |\n\n**WEIGHTED DECISION MATRIX:**\nApply weights from must-have features:\n- Total weighted score for {tool_a}: X/100\n- Total weighted score for {tool_b}: X/100\n\n**RECOMMENDATION:**\n- Best for {scenario_1}: {tool}\n- Best for {scenario_2}: {tool}\n- Best value: {tool}\n- Best scalability: {tool}\n\n**DECISION FRAMEWORK:**\nChoose {tool_a} if: {conditions}\nChoose {tool_b} if: {conditions}',
  'Business', 'ChatGPT', 'intermediate', false,
  ARRAY['saas-comparison', 'procurement', 'tco-analysis', 'enterprise', 'decision-framework'],
  145, 612, 2600, NOW()
),

-- ──────────────────────────────────────────────────────
-- 18. CHATGPT — TED-Style Talk Script
-- ──────────────────────────────────────────────────────
(
  'TED-Style Talk Script with Story Arc & Audience Engagement Cues',
  'Write a TED-format talk script with precise timing, story arc, stage direction, slide cues, and emotional beat mapping. For speakers preparing for conferences, TEDx, or company all-hands.',
  E'You are a TED talk coach who has prepared 40+ speakers for TEDx stages, including 5 talks with 1M+ views.\n\nWrite a {duration}-minute TED-style talk about "{talk_title}".\n\n**SPEAKER PROFILE:**\n- Name: {speaker_name}\n- Expertise: {expertise}\n- Speaking style: {style}\n- Personal story to incorporate: {personal_story}\n\n**AUDIENCE:**\n- Who: {audience_description}\n- Size: {audience_size}\n- What they believe now: {current_belief}\n- What you want them to believe after: {desired_belief}\n\n**TALK STRUCTURE (Kurt Vonnegut Story Arc):**\n\n**[0:00] OPENING — "The Moment" (60 seconds):**\n- Start with a SPECIFIC moment in time: "On {date}, at {time}, I was standing in {place}..."\n- No "Good morning" or "I''m here to talk about"\n- Create vivid sensory detail\n- [STAGE DIRECTION: Walk to center stage, no slides]\n\n**[1:00] THE PROBLEM — "The World Before" (3 minutes):**\n- Paint the problem with a concrete example\n- Use data: "{stat}" — [SLIDE: {slide_description}]\n- Make it personal: How does this affect THEM (the audience)?\n- Build tension: "And it''s getting worse because..."\n- [EMOTIONAL BEAT: Concern → Frustration]\n\n**[4:00] THE TURN — "But Then..." (2 minutes):**\n- The moment of discovery/insight\n- "That''s when I realized {insight}"\n- Counter-intuitive twist that challenges the status quo\n- [STAGE DIRECTION: Pause 3 seconds. Let it land.]\n- [EMOTIONAL BEAT: Surprise → Curiosity]\n\n**[6:00] THE SOLUTION — "The Idea Worth Spreading" (4 minutes):**\n- State the core idea in ONE sentence (your TED idea)\n- Support with 3 pillars:\n  - Pillar 1: {evidence_type} — [SLIDE: {visual}]\n  - Pillar 2: {example/case_study}\n  - Pillar 3: {scientific_backing}\n- Make it actionable: "Here''s what this means for you..."\n- [EMOTIONAL BEAT: Hope → Excitement]\n\n**[10:00] THE STORY — "Proof It Works" (3 minutes):**\n- Tell ONE powerful story of transformation\n- Character: {character}\n- Before state → Struggle → After state\n- Include dialogue: "She looked at me and said..."\n- [STAGE DIRECTION: Move to the left side of stage]\n- [EMOTIONAL BEAT: Empathy → Inspiration]\n\n**[13:00] THE CLOSE — "Your Turn" ({remaining_time} minutes):**\n- Circle back to the opening story\n- Challenge the audience: "Tomorrow morning, I want you to {specific_action}"\n- End with the strongest sentence of the talk\n- [STAGE DIRECTION: Return to center. Pause. Eye contact. Walk off.]\n- DO NOT say "Thank you" — let the audience start the applause\n\n**SPEAKER NOTES:**\n- Pace: {words_per_minute} WPM (aim for 140-160)\n- Pauses: Mark with [PAUSE] — minimum 5 strategic pauses\n- Emphasis words: **bold** for vocal stress\n- Humor points: {joke_opportunities}\n- Audience interaction: {interaction_moment}',
  'Content Writing', 'ChatGPT', 'advanced', false,
  ARRAY['ted-talk', 'public-speaking', 'conference', 'storytelling', 'presentation'],
  267, 934, 3800, NOW()
),

-- ──────────────────────────────────────────────────────
-- 19. CHATGPT — Design System Documentation
-- ──────────────────────────────────────────────────────
(
  'Design System Component Spec Document (Figma-to-Code Ready)',
  'Generate a design system component specification that bridges design and engineering with token definitions, interaction states, accessibility requirements, and code API documentation. For design system teams.',
  E'You are a design systems architect who has built systems at companies like Shopify (Polaris), GitHub (Primer), and Atlassian (Atlassian Design System).\n\nCreate a comprehensive component specification for the {component_name} component.\n\n**COMPONENT OVERVIEW:**\n- Name: {component_name}\n- Category: {category} (e.g., Data Display, Navigation, Input, Feedback)\n- Design system: {system_name}\n- Framework: {framework} (React/Vue/Svelte/Web Components)\n\n**1. ANATOMY:**\nDescribe each sub-element:\n| Element | Required | Description |\n|---------|----------|-------------|\n| {root} | Yes | Container element |\n| {element_1} | Yes/No | Description |\n| {element_2} | | |\n\n**2. VARIANTS:**\n| Variant | Use Case | Visual Difference |\n|---------|----------|-------------------|\n| {variant_1} | {when_to_use} | {visual_diff} |\n| {variant_2} | | |\n| {variant_3} | | |\n\n**3. DESIGN TOKENS:**\n```json\n{\n  "{component_name}": {\n    "border-radius": "{radius_token}",\n    "padding": "{spacing_token}",\n    "font-size": "{typography_token}",\n    "color-background": "{color_token}",\n    "color-text": "{color_token}",\n    "shadow": "{elevation_token}",\n    "transition": "{motion_token}"\n  }\n}\n```\n\n**4. INTERACTION STATES:**\n| State | Visual Change | Token Override |\n|-------|--------------|----------------|\n| Default | | |\n| Hover | | |\n| Focus | 2px ring, offset 2px | focus-ring-color |\n| Active/Pressed | | |\n| Disabled | opacity 0.4, cursor not-allowed | |\n| Loading | | |\n| Error | | |\n\n**5. ACCESSIBILITY (WCAG 2.2 AA):**\n- Role: {aria_role}\n- ARIA attributes: {aria_attributes}\n- Keyboard navigation:\n  | Key | Action |\n  |-----|--------|\n  | Tab | {action} |\n  | Enter/Space | {action} |\n  | Escape | {action} |\n  | Arrow keys | {action} |\n- Color contrast: {contrast_ratio} (minimum 4.5:1 for text)\n- Screen reader announcement: "{announcement_text}"\n- Focus management: {focus_behavior}\n\n**6. RESPONSIVE BEHAVIOR:**\n| Breakpoint | Behavior |\n|------------|----------|\n| Mobile (<640px) | {behavior} |\n| Tablet (640-1024px) | {behavior} |\n| Desktop (>1024px) | {behavior} |\n\n**7. CODE API:**\n```typescript\ninterface {ComponentName}Props {\n  /** {description} */\n  variant?: {variant_union_type};\n  /** {description} */\n  size?: ''sm'' | ''md'' | ''lg'';\n  /** {description} */\n  disabled?: boolean;\n  /** {description} */\n  children: React.ReactNode;\n  /** Callback fired on {event} */\n  on{Event}?: (event: {EventType}) => void;\n}\n```\n\n**8. USAGE GUIDELINES:**\n- DO: {best_practice_1}\n- DO: {best_practice_2}\n- DON''T: {anti_pattern_1}\n- DON''T: {anti_pattern_2}\n\n**9. RELATED COMPONENTS:**\n- Use {related_1} instead when {condition}\n- Combine with {related_2} for {pattern}',
  'Design', 'ChatGPT', 'advanced', true,
  ARRAY['design-system', 'component-spec', 'figma', 'accessibility', 'ui-engineering'],
  198, 712, 2900, NOW()
),

-- ──────────────────────────────────────────────────────
-- 20. CHATGPT — Weekly Sprint Planning with OKR Alignment
-- ──────────────────────────────────────────────────────
(
  'Weekly Sprint Planning with OKR Alignment & Energy Mapping',
  'Generate a structured weekly plan that maps tasks to quarterly OKRs, includes energy-level time blocking, deep work scheduling, and buffer time. For engineering managers and product teams using Agile.',
  E'You are a productivity coach who combines Agile sprint planning with Cal Newport''s deep work methodology and energy management science.\n\nCreate my weekly plan aligned to my OKRs.\n\n**MY CONTEXT:**\n- Role: {role}\n- Team size: {team_size}\n- Sprint: {sprint_number} of {total_sprints}\n- Work hours: {start_time} to {end_time}, {timezone}\n- Meeting-free blocks: {meeting_free_times}\n- Energy pattern: {energy_pattern} (e.g., "morning person — peak 9-12 AM")\n\n**QUARTERLY OKRs:**\n- O1: {objective_1}\n  - KR1: {key_result_1} (current: {current_value} / target: {target_value})\n  - KR2: {key_result_2}\n- O2: {objective_2}\n  - KR1: {key_result_3}\n\n**THIS WEEK''S PRIORITIES:**\n1. {priority_1} (OKR: {linked_okr})\n2. {priority_2} (OKR: {linked_okr})\n3. {priority_3} (OKR: {linked_okr})\n\n**CARRYOVER FROM LAST WEEK:**\n- {carryover_1}\n- {carryover_2}\n\n**BLOCKERS:**\n- {blocker_1}\n- {blocker_2}\n\n**GENERATE:**\n\n**1. WEEKLY OKR ALIGNMENT CHECK:**\n| Priority | Linked OKR | Impact on KR | Confidence (🟢🟡🔴) |\n\n**2. DAY-BY-DAY SCHEDULE:**\n\nFor each day (Monday-Friday):\n```\n{day}\n━━━━━━━━━━━━━━━━━━━━━\n🧠 Deep Work Block ({time}): {task} [OKR: {x}]\n📧 Admin/Email ({time}): Process inbox, Slack\n🤝 Meetings ({time}): {meeting_list}\n⚡ Quick Wins ({time}): {small_tasks}\n🔋 Buffer ({time}): Overflow + unexpected\n🏃 End-of-Day ({time}): Shutdown ritual + tomorrow prep\n```\n\n**3. ENERGY-TASK MAPPING:**\n| Energy Level | Best Time | Task Type | This Week''s Tasks |\n|-------------|-----------|-----------|-------------------|\n| 🔥 Peak | {peak_hours} | Deep work, coding, writing | {tasks} |\n| ⚡ High | {high_hours} | Collaboration, reviews | {tasks} |\n| 😐 Medium | {medium_hours} | Meetings, feedback | {tasks} |\n| 🔋 Low | {low_hours} | Admin, email, planning | {tasks} |\n\n**4. SPRINT VELOCITY CHECK:**\n- Story points committed: {points}\n- Historical velocity: {avg_velocity}\n- Risk assessment: {over/under/on-track}\n\n**5. WEEKLY REVIEW TEMPLATE (for Friday):**\n- What got done? (vs. planned)\n- What didn''t? Why?\n- Key learning this week:\n- Adjustment for next week:\n- Gratitude/win:',
  'Productivity', 'ChatGPT', 'intermediate', false,
  ARRAY['sprint-planning', 'okr', 'time-blocking', 'agile', 'productivity', 'deep-work'],
  301, 1276, 5200, NOW()
),

-- ──────────────────────────────────────────────────────
-- 21. CHATGPT — 90-Day Content Calendar for Multi-Platform
-- ──────────────────────────────────────────────────────
(
  '90-Day Multi-Platform Content Calendar with Repurposing Workflow',
  'Generate a complete 90-day content calendar spanning 4+ platforms with pillar content themes, repurposing chains (1 piece → 10+ micro-content), and performance benchmarks. For content teams and solopreneurs.',
  E'You are a content operations strategist who has scaled content programs from 0 to 500K+ monthly impressions.\n\nCreate a 90-day content calendar for {brand_name} in the {niche} niche.\n\n**BRAND CONTEXT:**\n- Platforms: {platforms_list} (e.g., Blog, YouTube, LinkedIn, Twitter, Instagram, TikTok, Newsletter)\n- Publishing frequency: {frequency_per_platform}\n- Team: {team_size} (1 = solopreneur)\n- Content goal: {primary_goal} (leads/brand awareness/community/sales)\n- Audience: {audience_description}\n- Existing best performers: {top_content_examples}\n\n**MONTH 1 THEME: "{month_1_theme}" (Awareness)**\n**MONTH 2 THEME: "{month_2_theme}" (Engagement)**\n**MONTH 3 THEME: "{month_3_theme}" (Conversion)**\n\n**PILLAR CONTENT STRATEGY (4 pillars per month):**\n\nFor each pillar piece, create a REPURPOSING CHAIN:\n```\n📝 Blog Post (2,000 words)\n └→ 🎥 YouTube Video (10 min)\n    └→ 📱 3x Instagram Reels (15-30 sec each)\n    └→ 🐦 Twitter/X Thread (10 tweets)\n    └→ 💼 LinkedIn Post (text)\n    └→ 📧 Newsletter section\n    └→ 🎵 2x TikTok clips\n    └→ 📊 1x Carousel (Instagram/LinkedIn)\n    └→ 💬 3x Quote graphics\n    └→ ❓ 1x Poll/Question post\n```\n\n**WEEKLY CALENDAR FORMAT:**\n\n| Day | Platform | Content Type | Topic | Pillar | Status |\n|-----|----------|-------------|-------|--------|--------|\n| Mon | Blog | Pillar article | {topic} | P1 | Draft |\n| Mon | LinkedIn | Text post | Key takeaway from article | P1 | |\n| Tue | Twitter | Thread | 10 insights from article | P1 | |\n| Tue | Instagram | Reel | Hook from article | P1 | |\n| Wed | YouTube | Long-form | Deep dive on {topic} | P2 | |\n| ... continue for full week | | | | | |\n\n(Generate all 13 weeks)\n\n**CONTENT MIX RATIO (per platform):**\n- Educational: 40%\n- Entertaining/relatable: 25%\n- Promotional: 15%\n- Community/UGC: 10%\n- Behind-the-scenes: 10%\n\n**PERFORMANCE BENCHMARKS (Month-over-Month targets):**\n| Metric | Month 1 Target | Month 2 Target | Month 3 Target |\n|--------|---------------|---------------|----------------|\n| Impressions | | | |\n| Engagement rate | | | |\n| Follower growth | | | |\n| Email signups | | | |\n| Website traffic | | | |\n\n**TOOLS & WORKFLOW:**\n- Scheduling: {suggested_tool}\n- Repurposing order: Pillar → Video → Short-form → Text → Graphics\n- Batch creation day: {batch_day}\n- Review/approval: {approval_process}',
  'Marketing', 'ChatGPT', 'advanced', false,
  ARRAY['content-calendar', 'multi-platform', 'repurposing', 'content-strategy', 'social-media'],
  256, 1489, 5800, NOW()
),

-- ──────────────────────────────────────────────────────
-- 22. CHATGPT — React Component with Tests & Storybook
-- ──────────────────────────────────────────────────────
(
  'Production-Ready React Component with Tests, Storybook & A11y',
  'Generate a complete React component package including TypeScript implementation, unit tests (Vitest), Storybook stories, accessibility audit, and performance considerations. For frontend engineers building design system components.',
  E'You are a senior frontend engineer at a company with a mature design system (similar to Shopify Polaris or Radix UI).\n\nBuild a production-ready {component_name} component.\n\n**REQUIREMENTS:**\n- Component: {component_name}\n- Variants: {variants_list}\n- Props interface: {props_description}\n- Behavior: {behavior_description}\n- Framework: React 18+ with TypeScript\n- Styling: {styling_approach} (CSS Modules / Tailwind / Styled Components / CSS-in-JS)\n- State management: {state_approach}\n\n**DELIVERABLE 1 — COMPONENT CODE:**\n```tsx\n// {ComponentName}.tsx\n// Include:\n// - Full TypeScript types with JSDoc comments\n// - forwardRef for DOM access\n// - Compound component pattern (if applicable)\n// - useCallback/useMemo where needed\n// - Proper cleanup in useEffect\n// - Error boundaries consideration\n```\n\n**DELIVERABLE 2 — UNIT TESTS (Vitest + Testing Library):**\n```tsx\n// {ComponentName}.test.tsx\n// Test coverage for:\n// - Renders without crashing\n// - Each variant renders correctly\n// - User interactions (click, keyboard, focus)\n// - Accessibility (role, aria attributes)\n// - Edge cases (empty props, overflow, null values)\n// - Async behavior (if applicable)\n// - Snapshot test\n// Minimum 90% coverage target\n```\n\n**DELIVERABLE 3 — STORYBOOK STORIES:**\n```tsx\n// {ComponentName}.stories.tsx\n// Include:\n// - Default story\n// - All variants\n// - Interactive controls (args)\n// - Playground story\n// - Dark mode variant\n// - Mobile viewport\n// - Composition example (with other components)\n```\n\n**DELIVERABLE 4 — ACCESSIBILITY AUDIT:**\n| Check | Status | Notes |\n|-------|--------|-------|\n| ARIA roles correct | ✅/❌ | |\n| Keyboard navigable | | |\n| Screen reader tested | | |\n| Color contrast 4.5:1+ | | |\n| Focus visible | | |\n| Reduced motion support | | |\n| Touch target 44x44px | | |\n\n**DELIVERABLE 5 — PERFORMANCE NOTES:**\n- Re-render analysis: When does this component re-render?\n- Memoization: What should be memoized?\n- Bundle size impact: Estimated KB\n- Lazy loading: Should this be code-split?\n\n**CONSTRAINTS:**\n- No external dependencies (except specified styling)\n- Must work with SSR (Next.js compatible)\n- Tree-shakeable exports\n- Zero console warnings in strict mode',
  'Coding', 'ChatGPT', 'advanced', true,
  ARRAY['react', 'typescript', 'testing', 'storybook', 'accessibility', 'design-system'],
  234, 1098, 4300, NOW()
),

-- ──────────────────────────────────────────────────────
-- 23. CHATGPT — Summarize Non-Fiction Book into Action Steps
-- ──────────────────────────────────────────────────────
(
  'Non-Fiction Book → 30-Day Action Plan Converter',
  'Transform any non-fiction book into a practical 30-day implementation plan with daily micro-actions, habit stacking suggestions, and accountability checkpoints. For lifelong learners who read but don''t implement.',
  E'You are a learning strategist who specialises in converting book knowledge into actionable behaviour change using James Clear''s habit stacking and BJ Fogg''s tiny habits methodology.\n\nTransform "{book_title}" by {author} into a 30-day action plan.\n\n**READER CONTEXT:**\n- Why reading this book: {motivation}\n- Current skill level in this area: {skill_level}\n- Available daily time for practice: {daily_time} minutes\n- Primary goal from this book: {primary_goal}\n\n**DELIVERABLE STRUCTURE:**\n\n**PART 1 — BOOK CORE (Executive Summary):**\n- One-sentence thesis: {thesis}\n- 5 key principles (ranked by impact):\n  1. {principle} — Impact: ⭐⭐⭐⭐⭐\n  2. ...\n- Mental model shift: "Before: {old_thinking} → After: {new_thinking}"\n\n**PART 2 — 30-DAY ACTION PLAN:**\n\n**Week 1 (Days 1-7): Foundation — "{theme}"**\n| Day | Micro-Action (≤{daily_time} min) | Habit Stack | Success Metric |\n|-----|----------------------------------|-------------|----------------|\n| 1 | {specific_action} | After {existing_habit}, I will {new_action} | {measurable_outcome} |\n| 2 | {specific_action} | | |\n| ... | | | |\n| 7 | **CHECKPOINT:** Reflect on {question} | | |\n\n**Week 2 (Days 8-14): Deepening — "{theme}"**\n(Same format, building on Week 1)\n\n**Week 3 (Days 15-21): Application — "{theme}"**\n(Real-world application of concepts)\n\n**Week 4 (Days 22-30): Mastery — "{theme}"**\n(Teaching others, creating systems)\n\n**PART 3 — ACCOUNTABILITY SYSTEM:**\n- Weekly check-in questions (4 questions)\n- Monthly review template\n- "Done" criteria: How do you know you''ve internalised this book?\n\n**PART 4 — QUICK REFERENCE CARD:**\n- Top 10 quotes with page numbers\n- 5 frameworks/models (visual description)\n- 3 books to read next (and why)\n\n**RULES:**\n- Every action must be specific and completable in {daily_time} minutes\n- No vague actions like "practice mindfulness" — instead: "Sit in chair, set timer for 5 min, focus on breath, count to 10, restart"\n- Include both thinking exercises AND doing exercises\n- Build difficulty progressively (tiny → small → medium)',
  'Learning', 'ChatGPT', 'beginner', false,
  ARRAY['book-summary', 'action-plan', 'habit-building', 'learning', 'self-improvement'],
  256, 1234, 4600, NOW()
),

-- ──────────────────────────────────────────────────────
-- 24. DALL-E — Brand Logo Concept in Multiple Styles
-- ──────────────────────────────────────────────────────
(
  'Brand Logo Concept Generator in 5 Distinct Styles (DALL-E 3)',
  'Generate logo concepts for a brand across 5 different design styles (minimal, geometric, mascot, wordmark, abstract) with specific colour palettes, typography direction, and usage specifications. For founders and designers in ideation phase.',
  E'Generate a professional logo concept for {brand_name}, a {brand_type} brand in the {industry} industry.\n\n**BRAND ATTRIBUTES:**\n- Core values: {values_list}\n- Personality: {personality_traits}\n- Target audience: {audience}\n- Competitors (to differentiate from): {competitors}\n\n**GENERATE 5 LOGO STYLES:**\n\n**Style 1 — Minimal/Clean:**\n{brand_name} logo, minimal design, clean lines, single weight stroke, {primary_color} on white background, negative space technique, inspired by Apple/Airbnb simplicity, scalable to favicon, vector-style flat design\n\n**Style 2 — Geometric/Abstract:**\n{brand_name} logo, geometric shapes, {shape_preference} forms, gradient from {color_1} to {color_2}, modern tech aesthetic, crystal/faceted look, inspired by Stripe/Notion branding, no text\n\n**Style 3 — Wordmark/Typography:**\n{brand_name} wordmark logo, custom lettering, {typography_style} font style, {weight} weight, letter-spacing tracked, {text_effect} effect on key letter, monochrome {color}, inspired by Google/FedEx/NASA logotype\n\n**Style 4 — Symbol + Wordmark Combo:**\n{brand_name} logo with icon, {icon_concept} symbol to the left, {font_style} typeface for text, {color_scheme} colour scheme, balanced composition, works at 16px and 512px, inspired by Slack/Shopify\n\n**Style 5 — Mascot/Character:**\n{brand_name} mascot logo, friendly {mascot_type} character, {emotion} expression, {color_palette} colours, rounded features, suitable for avatar and merchandise, inspired by Duolingo/Mailchimp mascot\n\n**TECHNICAL REQUIREMENTS FOR ALL:**\n- White background, centered\n- No text artifacts or misspellings\n- No realistic photography — flat/vector style only\n- Square format (1:1)\n- Should work in: full colour, single colour, reversed (white on dark)\n- Favicon test: Must be recognisable at 32x32px\n\n**NEGATIVE PROMPT:** No gradients on text, no 3D rendering, no photorealistic elements, no busy backgrounds, no clip art quality, no generic globe/arrow/swoosh clichés',
  'Design', 'DALL-E', 'beginner', false,
  ARRAY['logo-design', 'branding', 'dall-e-3', 'visual-identity', 'startup-branding'],
  312, 1567, 5400, NOW()
),

-- ──────────────────────────────────────────────────────
-- 25. GEMINI — Data Analysis & Visualization Script (Python)
-- ──────────────────────────────────────────────────────
(
  'Python Data Analysis Pipeline with Auto-Visualization (Gemini)',
  'Generate a complete Python data analysis pipeline with pandas, automated chart generation (matplotlib/plotly), statistical tests, and an executive summary. For data analysts working with CSV/Excel datasets.',
  E'You are a senior data analyst who has built analysis pipelines for Fortune 500 companies using Python.\n\nCreate a complete data analysis pipeline for my dataset.\n\n**DATASET CONTEXT:**\n- File: {filename} ({file_format})\n- Rows: ~{row_count}\n- Columns: {column_list_with_types}\n- Business context: {business_context}\n- Analysis goal: {analysis_goal}\n\n**GENERATE THE FOLLOWING PIPELINE:**\n\n**1. DATA LOADING & INSPECTION:**\n```python\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\n\n# Load data with proper dtypes\n# Handle encoding issues\n# Display shape, dtypes, first 5 rows\n# Check for duplicates\n# Memory usage optimization\n```\n\n**2. DATA CLEANING:**\n```python\n# Missing value analysis (% per column, pattern visualization)\n# Imputation strategy for each column:\n#   - Numerical: {strategy} (mean/median/KNN/forward-fill)\n#   - Categorical: {strategy} (mode/unknown/drop)\n# Outlier detection (IQR method + Z-score)\n# Data type conversions\n# Feature engineering opportunities\n```\n\n**3. EXPLORATORY DATA ANALYSIS (EDA):**\nGenerate these specific visualizations:\n\n```python\n# Fig 1: Distribution of {target_variable} (histogram + KDE)\n# Fig 2: Correlation heatmap (top 15 features)\n# Fig 3: {category_variable} breakdown (grouped bar chart)\n# Fig 4: Time series trend (if date column exists)\n# Fig 5: Top/Bottom 10 by {metric} (horizontal bar)\n# Fig 6: Scatter plot: {var_x} vs {var_y} with {color_by}\n# Fig 7: Box plots for outlier visualization\n# Fig 8: Pair plot for key numerical features\n```\n\nStyle all charts with:\n- {chart_style} theme\n- Consistent color palette: {colors}\n- Proper labels, titles, annotations\n- Export as PNG (300 DPI) and interactive HTML (Plotly)\n\n**4. STATISTICAL ANALYSIS:**\n```python\n# Descriptive stats table\n# Hypothesis test: {hypothesis}\n#   - Test: {test_type} (t-test/chi-square/ANOVA/Mann-Whitney)\n#   - p-value interpretation\n#   - Effect size (Cohen''s d / Cramér''s V)\n# Correlation analysis (Pearson + Spearman)\n# Confidence intervals for key metrics\n```\n\n**5. KEY FINDINGS:**\nGenerate a markdown cell with:\n- Top 5 insights (numbered, with supporting stats)\n- 3 actionable recommendations\n- Limitations and caveats\n- Suggested next steps for deeper analysis\n\n**6. EXECUTIVE SUMMARY:**\n```python\n# Auto-generate a 1-page summary with:\n# - Key metric highlights\n# - Trend direction arrows (↑↓→)\n# - Risk flags 🔴🟡🟢\n# - Data quality score\n```\n\n**OUTPUT FORMAT:**\n- Jupyter Notebook (.ipynb) ready to run\n- All cells should execute without errors\n- Include markdown headers between sections\n- Pin all package versions in requirements',
  'Coding', 'Gemini', 'intermediate', false,
  ARRAY['data-analysis', 'python', 'pandas', 'visualization', 'statistics', 'jupyter'],
  278, 1345, 5100, NOW()
);
