-- Seed data for prompts table
-- Run this migration to populate sample prompts

INSERT INTO public.prompts (title, description, prompt_text, category, ai_tool, difficulty, premium, tags, upvotes, copies, views, created_at) VALUES
('Professional LinkedIn Post Generator', 'Generate engaging LinkedIn posts for B2B content', 'Act as a LinkedIn content expert with 10+ years experience in B2B marketing. Create a compelling LinkedIn post about {topic} that will resonate with {audience}. Include:\n\n1. An attention-grabbing opening hook\n2. 3-5 key value points with bullets or emojis\n3. A call-to-action that encourages engagement\n4. Professional but conversational tone', 'Business', 'ChatGPT', 'beginner', false, ARRAY['linkedin', 'b2b', 'content', 'professional'], 234, 1523, 5400, NOW()),

('Photorealistic Portrait AI Generator', 'Create stunning photorealistic portraits with Midjourney', 'Create a photorealistic portrait of {subject} with the following specifications:\n\n- Professional studio lighting with soft key light\n- 85mm lens equivalent, f/1.4 aperture\n- Shallow depth of field with blurred background\n- {style} aesthetic\n- High detail skin texture\n- {color_grading} color grading\n- Shot on RED camera equivalent quality\n- Taken by {photographer_style} photographer', 'Design', 'Midjourney', 'intermediate', false, ARRAY['portrait', 'photography', 'realistic', 'midjourney'], 198, 987, 4200, NOW()),

('Full-Stack Code Reviewer Prompt', 'Get expert code review from Claude', 'You are a principal software engineer at a FAANG company with expertise in {language} and {framework}. Review the following code for:\n\n1. Security vulnerabilities (OWASP top 10)\n2. Performance optimization opportunities\n3. Code maintainability and readability\n4. Design pattern violations\n5. Potential bugs or edge cases\n\nCode to review:\n{code}\n\nProvide specific recommendations with explanations.', 'Coding', 'Claude', 'advanced', true, ARRAY['code', 'review', 'security', 'performance'], 176, 654, 3100, NOW()),

('Instagram Carousel Script Creator', 'Create engaging Instagram carousel scripts', 'Create a 10-slide Instagram carousel script for {topic}. Each slide should:\n\n- Have a compelling hook or pattern interrupt\n- Use simple, conversational language\n- Include relevant emojis\n- Be mobile-friendly (readable on small screens)\n- Build towards a strong CTA\n\nTarget audience: {audience}\nTone: {tone}\n\nProvide slide-by-slide breakdown with emoji suggestions.', 'Social Media', 'ChatGPT', 'beginner', false, ARRAY['instagram', 'carousel', 'social', 'content'], 312, 2341, 6500, NOW()),

('Email Drip Campaign Builder', 'Design high-converting email sequences', 'Design a {number_of_emails}-email drip campaign for {product} targeting {audience}. For each email, include:\n\n1. Subject line optimized for {open_rate}% open rate\n2. Preview text (50 chars)\n3. Email body with:\n   - Opening hook\n   - Problem statement\n   - Solution (your product)\n   - Social proof\n   - CTA\n4. Psychology principle used\n\nFocus on {goal} goal. Provide complete email copy ready to send.', 'Marketing', 'ChatGPT', 'intermediate', false, ARRAY['email', 'marketing', 'campaign', 'copywriting'], 145, 876, 2900, NOW()),

('Fantasy Landscape Generator Prompt', 'Create breathtaking fantasy landscapes', 'Generate a hyper-detailed fantasy landscape featuring:\n\n- Floating islands with intricate geography\n- Bioluminescent flora glowing at night\n- {terrain_type} with dramatic formations\n- Magical {color_palette} color scheme\n- Volumetric god rays piercing through clouds\n- {structure_type} in the background\n- Atmospheric perspective and haze\n- {weather_condition} weather\n\nStyle: {art_style}\nArtist inspiration: {artist_reference}', 'Design', 'Stable Diffusion', 'beginner', false, ARRAY['fantasy', 'landscape', 'art', 'ai-art'], 267, 1234, 4100, NOW()),

('Technical Documentation Writer', 'Generate comprehensive API documentation', 'Create detailed technical documentation for {api_name} API. For each endpoint, include:\n\n1. Endpoint path and HTTP method\n2. Purpose and use case\n3. Required authentication\n4. Request parameters with types\n5. Response schema (success and error)\n6. Code examples in {languages}:\n   - cURL\n   - Python\n   - JavaScript\n   - Go\n7. Rate limits\n8. Common errors and solutions\n\nFormat as Markdown. Make it beginner-friendly but comprehensive.', 'Coding', 'Claude', 'intermediate', true, ARRAY['documentation', 'api', 'technical', 'writing'], 89, 432, 1800, NOW()),

('YouTube Video Script Optimizer', 'Write YouTube scripts optimized for retention', 'Write a {video_length}-minute YouTube video script about {topic}. Structure:\n\n1. Hook (first 3 seconds) - Pattern interrupt that stops scroll\n2. Value proposition - Why they should watch\n3. Main content (3-4 sections with transitions)\n4. Pattern breaks (jokes, visual cues, B-roll suggestions)\n5. Call-to-action (Subscribe, like, comment)\n\nTarget audience: {audience}\nVideo goal: {goal}\nTone: {tone}\n\nOptimize for viewer retention and engagement metrics.', 'Content Writing', 'ChatGPT', 'beginner', false, ARRAY['youtube', 'video', 'script', 'content'], 203, 1567, 5100, NOW()),

('Brand Identity Creation Framework', 'Develop complete brand strategy', 'Act as a strategic brand consultant. Develop a comprehensive brand identity for {company_name}:\n\n1. Brand positioning and market differentiation\n2. Mission statement (inspiring, concise)\n3. Brand values and personality traits\n4. Target audience personas (3-5)\n5. Brand voice and messaging guidelines\n6. Visual identity recommendations (colors, typography)\n7. Brand story and origin narrative\n8. Competitor differentiation\n9. Brand guidelines outline\n10. Launch strategy\n\nCompany: {company_name}\nIndustry: {industry}\nStage: {stage}', 'Business', 'ChatGPT', 'advanced', true, ARRAY['brand', 'strategy', 'business', 'marketing'], 156, 678, 2300, NOW()),

('SEO Blog Post Outline Generator', 'Create SEO-optimized blog post outlines', 'Generate a comprehensive blog post outline for the keyword "{keyword}". Include:\n\n1. Meta title (50-60 chars) - Include keyword\n2. Meta description (150-160 chars)\n3. H1 title with keyword\n4. Introduction hook\n5. Main sections (H2s) with subsections (H3s)\n6. Key points to cover in each section\n7. LSI keywords to naturally incorporate\n8. Internal linking opportunities\n9. FAQ section (5-7 common questions)\n10. Strong conclusion with CTA\n\nTarget audience: {audience}\nSearch intent: {intent}\nWord count target: {word_count}\n\nOptimize for both search engines and user experience.', 'Content Writing', 'ChatGPT', 'intermediate', false, ARRAY['seo', 'blog', 'content', 'writing'], 289, 2156, 6800, NOW()),

('Product Launch Campaign Prompt', 'Plan comprehensive product launches', 'Create a {duration}-day product launch campaign for {product_name}. Include:\n\n1. Pre-launch phase (teaser strategy)\n2. Launch day plan (timing, channels, messaging)\n3. Post-launch momentum (Day 1-30)\n4. Channel strategy:\n   - Email sequences\n   - Social media content\n   - Paid ads angles\n   - PR angles\n5. Success metrics and KPIs\n6. Contingency plans\n7. Team responsibilities\n\nTarget audience: {audience}\nBudget: {budget}\nGoal: {goal_metric}', 'Marketing', 'ChatGPT', 'advanced', false, ARRAY['product', 'launch', 'marketing', 'strategy'], 167, 745, 2800, NOW()),

('Podcast Episode Script Writer', 'Generate engaging podcast scripts', 'Write a {duration}-minute podcast episode script for {podcast_name}. Include:\n\n1. Cold open (Hook listener immediately)\n2. Intro segment (3-5 minutes)\n3. Guest introduction (if applicable)\n4. Main content (5-7 segments with transitions)\n5. Stories or examples to illustrate points\n6. Listener call-to-action\n7. Sponsor integration (natural, value-add)\n8. Outro and next episode teaser\n9. Background music cues\n\nTopic: {topic}\nTone: {tone}\nTarget listener: {audience}\n\nMake it conversational, engaging, and valuable.', 'Content Writing', 'ChatGPT', 'intermediate', false, ARRAY['podcast', 'script', 'audio', 'content'], 134, 567, 2100, NOW());

-- Insert more prompts for variety (continuing from previous 12)
INSERT INTO public.prompts (title, description, prompt_text, category, ai_tool, difficulty, premium, tags, upvotes, copies, views, created_at) VALUES
('Programming Interview Prep', 'Prepare for technical interviews', 'Act as a senior software engineer conducting a technical interview. Ask me interview questions for the {position} role at {company_level} company. Focus on:\n\n1. Data structures and algorithms\n2. System design (if senior level)\n3. Coding problem solving\n4. Behavioral questions\n5. Problem-solving approach\n\nAfter I answer, provide:\n- Evaluation of my answer\n- What I did well\n- What could be improved\n- Alternative approaches\n\nStart with a problem appropriate for my level.', 'Coding', 'ChatGPT', 'advanced', false, ARRAY['interview', 'coding', 'learning', 'technical'], 198, 892, 3400, NOW()),

('Instagram Caption Generator', 'Create viral Instagram captions', 'Create a {style} Instagram caption for my post about {topic}. Requirements:\n\n- Hook in first line (stop the scroll)\n- {word_count} words\n- Include relevant emojis (not overused)\n- Include {hashtag_count} hashtags\n- Call-to-action (tag a friend, visit link, etc)\n- Hashtags should be in comment, not caption\n- Optimize for {algorithm} (reach/engagement/saves)\n\nTone: {tone}\nAudience: {audience}\nGoal: {goal}', 'Social Media', 'ChatGPT', 'beginner', false, ARRAY['instagram', 'social', 'content', 'copywriting'], 412, 3200, 8900, NOW()),

('Book Summary Generator', 'Create comprehensive book summaries', 'Summarize the book "{book_title}" by {author} as if explaining it to a {audience}. Include:\n\n1. Executive summary (1 paragraph)\n2. Main themes and key concepts\n3. Key chapters breakdown\n4. Important quotes and lessons\n5. How to apply the lessons\n6. Strengths and limitations\n7. Similar books to read\n8. Overall rating and recommendation\n\nStyle: {style}\nDepth: {depth}\nFocus on: {focus_area}', 'Learning', 'Claude', 'beginner', false, ARRAY['books', 'learning', 'summary', 'education'], 156, 534, 2500, NOW()),

('Research Paper Summarizer', 'Break down complex research papers', 'Summarize the research paper on {topic}. Structure your response as:\n\n1. Title and authors\n2. One-sentence summary\n3. Problem being solved\n4. Methodology used\n5. Key findings and results\n6. Implications and impact\n7. Limitations and future work\n8. How it relates to {related_field}\n9. Key statistics and numbers\n10. Accessibility rating (easy/moderate/difficult)\n\nMake it understandable to someone without expertise in {field}.', 'Learning', 'Claude', 'intermediate', false, ARRAY['research', 'academic', 'science', 'learning'], 123, 456, 1900, NOW()),

('Job Application Letter Writer', 'Generate personalized job application letters', 'Write a compelling application letter for the {position} role at {company}. Include:\n\n1. Strong opening that shows you know the company\n2. Your relevant experience and skills\n3. Why you''re passionate about the role\n4. Specific examples of your achievements\n5. How you align with company values\n6. Your unique value proposition\n7. Call-to-action for next step\n\nYour experience: {experience}\nKey achievements: {achievements}\nCompany mission: {company_mission}\n\nMake it personalized and compelling, not generic.', 'Career', 'ChatGPT', 'beginner', false, ARRAY['job', 'application', 'career', 'writing'], 189, 723, 3500, NOW()),

('Product Comparison Framework', 'Compare products systematically', 'Compare {product_a} vs {product_b}. Create a comprehensive comparison including:\n\n1. Feature comparison table\n2. Pricing breakdown\n3. Pros and cons of each\n4. Best use cases\n5. Performance metrics\n6. User reviews summary\n7. Integration options\n8. Customer support quality\n9. Learning curve assessment\n10. Overall recommendation\n\nUse case: {use_case}\nBudget: {budget}\nPriority factors: {priorities}', 'Business', 'ChatGPT', 'intermediate', false, ARRAY['comparison', 'analysis', 'business', 'decision'], 145, 612, 2600, NOW()),

('Public Speaking Script Creator', 'Write engaging speech scripts', 'Write a {duration}-minute speech about {topic} for {audience} at {event_type}. Include:\n\n1. Attention-grabbing opening\n2. Clear thesis/purpose\n3. 3-5 main points with stories/examples\n4. Transitions between points\n5. Memorable conclusion with call-to-action\n6. Speaker notes with pacing\n7. Joke opportunities\n8. Pause points for effect\n\nTone: {tone}\nKey message: {key_message}\nGoal: {goal}', 'Content Writing', 'ChatGPT', 'intermediate', false, ARRAY['speaking', 'speech', 'presentation', 'communication'], 167, 534, 2200, NOW()),

('Design Brief Template', 'Create comprehensive design briefs', 'Create a detailed design brief for {project_type}. Include:\n\n1. Project overview and goals\n2. Target audience and personas\n3. Competitor analysis (2-3 competitors)\n4. Design requirements\n5. Style preferences and references\n6. Color palette guidance\n7. Typography direction\n8. Tone and messaging\n9. Deliverables list\n10. Timeline and milestones\n11. Success metrics\n12. Budget considerations\n\nProject: {project_name}\nBrand: {brand_name}\nScope: {scope}', 'Design', 'ChatGPT', 'intermediate', false, ARRAY['design', 'brief', 'professional', 'business'], 98, 412, 1600, NOW()),

('Weekly Planner Prompt', 'Plan productive weeks systematically', 'Help me plan a productive week. Provide:\n\n1. Weekly goal setting (1-3 main goals)\n2. Day-by-day breakdown\n3. Time blocking suggestions\n4. Priority tasks (MIT - Most Important Tasks)\n5. Time for deep work vs meetings\n6. Break and recovery time\n7. Progress tracking method\n8. Weekly review template\n9. Adjustment recommendations\n10. Motivation and accountability tips\n\nMy goals: {goals}\nChallenges: {challenges}\nWork style: {work_style}\n\nOptimize for productivity and well-being.', 'Productivity', 'ChatGPT', 'beginner', false, ARRAY['planning', 'productivity', 'time-management', 'organization'], 201, 876, 4200, NOW()),

('Content Calendar Planner', 'Generate content marketing calendars', 'Create a {duration}-month content calendar for {platform} for the {niche} niche. Include:\n\n1. Content themes for each month\n2. Weekly content mix (educational, promotional, entertaining)\n3. Specific content ideas (20+ posts)\n4. Hashtag strategy\n5. Posting schedule and times\n6. Engagement strategies\n7. Collaboration opportunities\n8. Analytics tracking method\n9. Seasonal considerations\n10. Holidays and special events to feature\n\nTarget audience: {audience}\nGoals: {goals}\nPlatform algorithm focus: {focus}', 'Marketing', 'ChatGPT', 'intermediate', false, ARRAY['content', 'marketing', 'social', 'planning'], 156, 689, 2800, NOW());
